### ISSUE TITLE
libdyldcache-1.0.pc.in was renamed to libdyldcache-1.0.pc

### ISSUE THREAD

**Issue by blurbdust** [OpenJailbreak/libdyldcache#1]
autogen.sh fails with `config.status: error: cannot find input file: 'Makefile.in'` since `configure.ac:21: error: required file 'libdyldcache-1.0.pc.in' not found`

Makefile.in should be generated from libdyldcache-1.0.pc.in. Once libdyldcache-1.0.pc was renamed to libdyldcache-1.0.pc.in everything worked.

**Comment by posixninja** [comment]
I apologize, I fixed this on my end, seems I forgot to push the changes. thank you for the heads up
